---
include:
  - board: nice_nano_v2
    shield: sofle_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME="Sofle" -DCONFIG_ZMK_SLEEP=y
    artifact-name: sofle_left
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    cmake-args: -DCONFIG_ZMK_SLEEP=y
    artifact-name: sofle_right
